Repository MultiEmail/frontend, pull requests merged in 2022-10, with the labels that each got.

#21 [docs] : Add LICENSE + CONTRIBUTING.md links to readme
  README.md
Labels: documentation, hacktoberfest-accepted

#32 refactor: improved folder structure
  .commitlintrc.json
  .husky/commit-msg
  package.json
  src/App.test.tsx
  src/App.tsx
  src/actions/.gitkeep
  src/app/hooks.ts
  src/app/store.ts
  src/components/NavBar.tsx
  src/components/nav/Nav.tsx
  src/hooks/useAppDispatch.ts
  src/hooks/useAppSelector.ts
  src/index.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/pages/Verification.tsx
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/signup/Signup.tsx
  src/pages/verification/Verification.tsx
  src/reducers/.gitkeep
  src/slices/.gitkeep
  src/store.ts
  src/types/enums.ts
  src/types/interfaces.ts
  src/types/types.ts
  yarn.lock
Labels: hacktoberfest-accepted, refactor

#34 feat: added 404 page
  src/App.tsx
  src/assets/photos/not_found.svg
  src/pages/not_found/Not_Found.tsx
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#38 [UPDATE] issue template config to enable support for blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: hacktoberfest-accepted

#42 feat: signup API integration
  .env.example
  .gitignore
  .vscode/settings.json
  package.json
  src/actions/auth.actions.ts
  src/hooks/useAppDispatch.ts
  src/hooks/useAppSelector.ts
  src/hooks/useUpdateObjectState.ts
  src/pages/signup/Signup.tsx
  src/store.ts
  src/types/enums.ts
  src/types/interfaces.ts
  src/types/types.ts
  src/utils/api.util.ts
  tailwind.config.js
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#45 feat: created UI for signup and login
  package.json
  src/assets/photos/vector-login.svg
  src/assets/photos/vector-signup.svg
  src/assets/photos/vector-verify.svg
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/signup/Signup.tsx
  yarn.lock
Labels: enhancement

#57 feat: api integration for login
  src/actions/auth.actions.ts
  src/pages/login/Login.tsx
Labels: enhancement, hacktoberfest-accepted

#64 feat: Added hover effect on back button in login and signup page
  src/index.css
  src/pages/login/Login.tsx
  src/pages/signup/Signup.tsx
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#74 feat: added docker support
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement, hacktoberfest-accepted

#91 fix: Issue #47, #67, #66
  package.json
  src/App.tsx
  src/actions/auth.actions.ts
  src/components/nav/Nav.tsx
  src/index.css
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/signup/Signup.tsx
  src/pages/verification/Verification.tsx
  yarn.lock
Labels: hacktoberfest-accepted

#97 fix: added back Tooltip and NavbarLayout, minor changes to fix UI
  src/App.tsx
  src/components/nav/NavbarLayout.tsx
  src/components/tooltip/Tooltip.tsx
  src/pages/login/Login.tsx
  src/pages/signup/Signup.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#100 feat: allow to use either username or email
  src/actions/auth.actions.ts
  src/pages/login/Login.tsx
Labels: enhancement, hacktoberfest-accepted

#102 fix: wrong docker volume mounts
  docker-compose.yml
Labels: bug

#112 chore: frontend enhancement
  .all-contributorsrc
  .commitlintrc.json
  .dockerignore
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/security_issue.yml
  .github/ISSUE_TEMPLATE/test.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/commit-msg
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile
  LICENSE
  README.md
  public/index.html
  public/manifest.json
  public/robots.txt
  renovate.json
  src/App.test.tsx
  src/App.tsx
  src/actions/.gitkeep
  src/actions/auth.actions.ts
  src/actions/request.actions.ts
  src/components/nav/Nav.tsx
  src/components/nav/NavbarLayout.tsx
  src/components/tooltip/Tooltip.tsx
  src/hooks/useAppDispatch.ts
  src/hooks/useAppSelector.ts
  src/hooks/useUpdateObjectState.ts
  src/index.css
  src/index.tsx
  src/pages/about/About.tsx
  src/pages/about/about.tsx
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/not_found/Not_Found.tsx
  src/pages/password_reset/PasswordReset.tsx
  src/pages/signup/Signup.tsx
  src/pages/support/Support.tsx
  src/pages/verification/Verification.tsx
  src/react-app-env.d.ts
  src/reducers/.gitkeep
  src/reportWebVitals.ts
  src/setupTests.ts
  src/slices/.gitkeep
  src/store.ts
  src/utils/api.util.ts
  tailwind.config.js
  tsconfig.json
  typedoc.json
Labels: enhancement, fixed, hacktoberfest-accepted

#121 All theme colors added to tailwind.config
  tailwind.config.js
Labels: enhancement
